Provide Job and buildpack support (#60)

diff --git a/.tekton/tasks/task-deploy-to-code-engine.yml b/.tekton/tasks/task-deploy-to-code-engine.yml
--- a/.tekton/tasks/task-deploy-to-code-engine.yml
+++ b/.tekton/tasks/task-deploy-to-code-engine.yml
@@ -55,6 +55,12 @@ spec:
     - name: deployment-timeout
       description: maximum timeout for the application deployment.
       default: "300"
+    - name: deployment-type
+      description:  Specifies the type of deployment. Valid values are 'application' and 'job'. 
+      default: "application"
+    - name: maxexecutiontime
+      description: The maximum execution time in seconds for runs of the job. 
+      default: "7200"
   results:
     - name: app-url
       description: The running application's URL (obtained from APP_URL variable set by the executed script)
@@ -87,24 +93,24 @@ spec:
         set -e -o pipefail
 
         if [ $(params.pipeline-debug) == 1 ]; then
-          env
-          pwd
-          ls -l
-          echo "=== cat /artifacts/_toolchain.json ==="
-          cat /artifacts/_toolchain.json
-          echo ""
-          echo "======================================"
-          trap env EXIT
-          set -x
+            env
+            pwd
+            ls -l
+            echo "=== cat /artifacts/_toolchain.json ==="
+            cat /artifacts/_toolchain.json
+            echo ""
+            echo "======================================"
+            trap env EXIT
+            set -x
         fi
 
         # SETUP BEGIN
         ibmcloud config --check-version false
         if [ "$(params.region)" ]; then
-          # if cluster region is in the 'ibm:yp:<region>' just keep the region part
-          IBM_CLOUD_REGION=$(echo "$(params.region)" | awk -F ':' '{print $NF;}')
+            # if cluster region is in the 'ibm:yp:<region>' just keep the region part
+            IBM_CLOUD_REGION=$(echo "$(params.region)" | awk -F ':' '{print $NF;}')
         else
-          IBM_CLOUD_REGION=$(jq -r '.region_id' /artifacts/_toolchain.json | awk -F: '{print $3}')
+            IBM_CLOUD_REGION=$(jq -r '.region_id' /artifacts/_toolchain.json | awk -F: '{print $3}')
         fi
 
         ibmcloud login -a $(params.ibmcloud-api) -r $IBM_CLOUD_REGION --apikey $PIPELINE_BLUEMIX_API_KEY
@@ -121,11 +127,11 @@ spec:
 
         echo "Check Code Engine project availability"
         if ibmcloud ce proj get -n $(params.code-engine-project); then
-          echo -e "Code Engine project $(params.code-engine-project) found."
+            echo -e "Code Engine project $(params.code-engine-project) found."
         else
-          echo -e "No Code Engine project with the name $(params.code-engine-project) found. Creating new project..."
-          ibmcloud ce proj create -n $(params.code-engine-project)
-          echo -e "Code Engine project $(params.code-engine-project) created."
+            echo -e "No Code Engine project with the name $(params.code-engine-project) found. Creating new project..."
+            ibmcloud ce proj create -n $(params.code-engine-project)
+            echo -e "Code Engine project $(params.code-engine-project) created."
         fi
 
         echo "Loading Kube config..."
@@ -147,96 +153,134 @@ spec:
         IMAGE_PULL_SECRET_NAME="ibmcloud-toolchain-${PIPELINE_TOOLCHAIN_ID}-${REGISTRY_URL}"
 
         if ! kubectl get secret ${IMAGE_PULL_SECRET_NAME}; then
-          echo -e "${IMAGE_PULL_SECRET_NAME} not found, creating it"
-          # for Container Registry, docker username is 'token' and email does not matter
-          kubectl create secret docker-registry ${IMAGE_PULL_SECRET_NAME} --docker-server=${REGISTRY_URL} --docker-password=${PIPELINE_BLUEMIX_API_KEY} --docker-username=iamapikey --docker-email=a@b.com
+            echo -e "${IMAGE_PULL_SECRET_NAME} not found, creating it"
+            # for Container Registry, docker username is 'token' and email does not matter
+            kubectl create secret docker-registry ${IMAGE_PULL_SECRET_NAME} --docker-server=${REGISTRY_URL} --docker-password=${PIPELINE_BLUEMIX_API_KEY} --docker-username=iamapikey --docker-email=a@b.com
         fi
 
-        if ibmcloud ce app get -n $(params.app-name) | grep Age; then
-          echo "Code Engine app with name $(params.app-name) found, updating it"
-          ibmcloud ce app update -n $(params.app-name) \
-            -i $(params.image-repository):$(params.image-tags) \
-            --rs ${IMAGE_PULL_SECRET_NAME} \
-            -w=false \
-            --cpu $(params.cpu) \
-            --max $(params.max-scale) \
-            --min $(params.min-scale) \
-            -m $(params.memory) \
-            -p $(params.port)
+        if [[ "$(params.deployment-type)" == "application" ]]; then
+            echo "Deploying your code as Code Engine application...."
+
+            if ibmcloud ce app get -n $(params.app-name) | grep Age; then
+                echo "Code Engine app with name $(params.app-name) found, updating it"
+                ibmcloud ce app update -n $(params.app-name) \
+                    -i $(params.image-repository):$(params.image-tags) \
+                    --rs ${IMAGE_PULL_SECRET_NAME} \
+                    -w=false \
+                    --cpu $(params.cpu) \
+                    --max $(params.max-scale) \
+                    --min $(params.min-scale) \
+                    -m $(params.memory) \
+                    -p $(params.port)
+            else
+                echo "Code Engine app with name $(params.app-name) not found, creating it"
+                ibmcloud ce app create -n $(params.app-name) \
+                    -i $(params.image-repository):$(params.image-tags) \
+                    --rs ${IMAGE_PULL_SECRET_NAME} \
+                    -w=false \
+                    --cpu $(params.cpu) \
+                    --max $(params.max-scale) \
+                    --min $(params.min-scale) \
+                    -m $(params.memory) \
+                    -p $(params.port)
+            fi
+
+            # Bind services, if any
+            while read; do
+                NAME=$(echo "$REPLY" | jq -j '.key')
+                PREFIX=$(echo "$REPLY" | jq -j '.value')
+
+                if ! ibmcloud ce app get -n $(params.app-name) | grep "$NAME"; then
+                    ibmcloud ce app bind -n $(params.app-name) --si "$NAME" -p "$PREFIX" -w=false
+                fi
+            done < <(jq -c 'to_entries | .[]' <<<$(echo $(params.service-bindings) | base64 -d))
+
+            echo "Checking if application is ready..."
+            KUBE_SERVICE_NAME=$(params.app-name)
+
+            DEPLOYMENT_TIMEOUT=$(params.deployment-timeout)
+            echo "Timeout for the application deployment is ${DEPLOYMENT_TIMEOUT}"
+            ITERATION=0
+            while [[ "${ITERATION}" -le "${DEPLOYMENT_TIMEOUT}" ]]; do
+                sleep 1
+
+                SVC_STATUS_READY=$(kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "True")')
+
+                SVC_STATUS_NOT_READY=$(kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "False")')
+
+                SVC_STATUS_UNKNOWN=$(kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "Unknown")')
+
+                if [ \( -n "$SVC_STATUS_NOT_READY" \) -o \( -n "$SVC_STATUS_UNKNOWN" \) ]; then
+                    echo "Application not ready, retrying"
+                elif [ -n "$SVC_STATUS_READY" ]; then
+                    echo "Application is ready"
+                    break
+                else
+                    echo "Application status unknown, retrying"
+                fi
+                ITERATION="${ITERATION}"+1
+            done
+
+            echo "Application service details:"
+            kubectl describe ksvc/${KUBE_SERVICE_NAME}
+            if [ \( -n "$SVC_STATUS_NOT_READY" \) -o \( -n "$SVC_STATUS_UNKNOWN" \) ]; then
+                echo "Application is not ready after waiting maximum time"
+                exit 1
+            fi
+
+            # Determine app url for polling from knative service
+            TEMP_URL=$(kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status.url')
+            echo "Application status URL: $TEMP_URL"
+            TEMP_URL=${TEMP_URL%\"} # remove end quote
+            TEMP_URL=${TEMP_URL#\"} # remove beginning quote
+            APPLICATION_URL=$TEMP_URL
+            if [ -z "$APPLICATION_URL" ]; then
+                echo "Deploy failed, no URL found for application"
+                exit 1
+            fi
+            echo "Application is available"
+            echo "=========================================================="
+            echo -e "View the application at: $APPLICATION_URL"
+
+            # Record task results
+            echo -n "$APPLICATION_URL" >$(results.app-url.path)
+
         else
-          echo "Code Engine app with name $(params.app-name) not found, creating it"
-          ibmcloud ce app create -n $(params.app-name) \
-            -i $(params.image-repository):$(params.image-tags) \
-            --rs ${IMAGE_PULL_SECRET_NAME} \
-            -w=false \
-            --cpu $(params.cpu) \
-            --max $(params.max-scale) \
-            --min $(params.min-scale) \
-            -m $(params.memory) \
-            -p $(params.port)
+            echo "Deploying your code as Code Engine job......"
+            if ibmcloud ce job get --name $(params.app-name); then
+                echo "Code Engine job with name $(params.app-name) found, updating it"
+                ibmcloud ce job update -n $(params.app-name) \
+                    -i $(params.image-repository):$(params.image-tags) \
+                    --rs ${IMAGE_PULL_SECRET_NAME} \
+                    --cpu $(params.cpu) \
+                    -m $(params.memory) \
+                    --maxexecutiontime "$(params.maxexecutiontime)"
+            else
+                echo "Code Engine job with name $(params.app-name) not found, creating it"
+
+                ibmcloud ce job create -n "$(params.app-name)" \
+                    -i "$(params.image-repository):$(params.image-tags)" \
+                    --rs "${IMAGE_PULL_SECRET_NAME}" \
+                    --cpu "$(params.cpu)" \
+                    -m "$(params.memory)" \
+                    --maxexecutiontime "$(params.maxexecutiontime)"
+            fi
+
+            # Bind services, if any
+            while read; do
+                NAME=$(echo "$REPLY" | jq -j '.key')
+                PREFIX=$(echo "$REPLY" | jq -j '.value')
+
+                if ! ibmcloud ce job get -n $(params.app-name) | grep "$NAME"; then
+                    ibmcloud ce job bind -n $(params.app-name) --si "$NAME" -p "$PREFIX" -w=false
+                fi
+            done < <(jq -c 'to_entries | .[]' <<<$(echo $(params.service-bindings) | base64 -d))
+            echo "Code Engine Job created/updated successfully."
+            # Record task results
+            echo -n "Code Engine Job created/updated" >$(results.app-url.path)
+
         fi
 
-        # Bind services, if any
-        while read;
-        do
-          NAME=$(echo "$REPLY" | jq -j '.key')
-          PREFIX=$(echo "$REPLY" | jq -j '.value')
-
-          if ! ibmcloud ce app get -n $(params.app-name) | grep "$NAME"; then
-            ibmcloud ce app bind -n $(params.app-name) --si "$NAME" -p "$PREFIX" -w=false
-          fi
-        done < <(jq -c 'to_entries | .[]' <<< $(echo $(params.service-bindings) | base64 -d))
-
-        echo "Checking if application is ready..."
-        KUBE_SERVICE_NAME=$(params.app-name)
-        
-        DEPLOYMENT_TIMEOUT=$(params.deployment-timeout)
-        echo "Timeout for the application deployment is ${DEPLOYMENT_TIMEOUT}"
-        ITERATION=0
-        while [[ "${ITERATION}" -le "${DEPLOYMENT_TIMEOUT}" ]]
-        do
-          sleep 1
-
-          SVC_STATUS_READY=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "True")' )
-
-          SVC_STATUS_NOT_READY=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "False")' )
-
-          SVC_STATUS_UNKNOWN=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status?.conditions[]?.status?|select(. == "Unknown")' )
-
-          if [ \( -n "$SVC_STATUS_NOT_READY" \) -o \( -n "$SVC_STATUS_UNKNOWN" \) ]; then
-            echo "Application not ready, retrying"
-          elif [ -n "$SVC_STATUS_READY" ]; then
-            echo "Application is ready"
-            break
-          else
-            echo "Application status unknown, retrying"
-          fi
-          ITERATION="${ITERATION}"+1
-        done
-
-        echo "Application service details:"
-        kubectl describe ksvc/${KUBE_SERVICE_NAME}
-        if [ \( -n "$SVC_STATUS_NOT_READY" \) -o \( -n "$SVC_STATUS_UNKNOWN" \) ]; then
-          echo "Application is not ready after waiting maximum time"
-          exit 1
-        fi
-
-        # Determine app url for polling from knative service
-        TEMP_URL=$( kubectl get ksvc/${KUBE_SERVICE_NAME} -o json | jq '.status.url' )
-        echo "Application status URL: $TEMP_URL"
-        TEMP_URL=${TEMP_URL%\"} # remove end quote
-        TEMP_URL=${TEMP_URL#\"} # remove beginning quote
-        APPLICATION_URL=$TEMP_URL
-        if [ -z "$APPLICATION_URL" ]; then
-          echo "Deploy failed, no URL found for application"
-          exit 1
-        fi
-        echo "Application is available"
-        echo "=========================================================="
-        echo -e "View the application at: $APPLICATION_URL"
-
-        # Record task results
-        echo -n "$APPLICATION_URL" > $(results.app-url.path)
       volumeMounts:
         - mountPath: /cd-config
           name: cd-config-volume
